language: c
dist: xenial
sudo: required

addons:
  apt:
    packages:
    - curl
    - libcurl4-gnutls-dev
    - ca-certificates
    - software-properties-common 
    - python-software-properties
    - gnupg-curl

compiler:
  - gcc

env:
  - PG_VERSION=10
  - PG_VERSION=11
  - PG_VERSION=12

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql-9.1
  - sudo apt-get -y --purge remove postgresql-9.2
  - sudo apt-get -y --purge remove postgresql-9.3
  - sudo apt-get -y --purge remove postgresql-9.4
  - sudo apt-get -y --purge remove postgresql-9.5
  - sudo apt-get -y --purge remove postgresql-9.6
  - sudo apt-get -y --purge remove postgresql-common
  - sudo apt-get -y autoremove
  - sudo rm -rf /var/lib/postgresql
  - apt-key adv --fetch-keys https://www.postgresql.org/media/keys/ACCC4CF8.asc
  - sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main $PG_VERSION"    
  - sudo apt-get update -qq
  - sudo apt-get -y install postgresql-$PG_VERSION postgresql-client-$PG_VERSION postgresql-server-dev-$PG_VERSION
  - sudo cp ci/pg_hba.conf /etc/postgresql/$PG_VERSION/main/pg_hba.conf
  - sudo /etc/init.d/postgresql reload


script:
  - make
  - sudo make install
  - PGUSER=postgres PGPORT=5432 make installcheck || (cat regression.diffs && /bin/false)

